### PR TITLE
Incorrect usage is corrected for global variable

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Incorrect usage of global variable is corrected
Spec file changes for python3 conversion

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@amohan@redhat.com, @nthomas-redhat, @anmolbabu , @cloudbehl  Please review

**Comment by cloudbehl** [comment]
@TimothyAsirJeyasing can you fix the `Codacy/PR Quality Review` and also why CI tests are failing?

File: tendrl/commons/tests/flows/expand_cluster/test_ec_init.py [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import __builtin__
+import builtins
```
Comment (cloudbehl) [inline tendrl/commons/tests/flows/expand_cluster/test_ec_init.py:1]: use builtins instead of __builtin__ in code also. Check line 50

**Review by cloudbehl — CHANGES_REQUESTED** [review]
Please make this change in all the test files.

File: tendrl/commons/tests/flows/expand_cluster/test_ec_init.py (hunk 1 above)
Comment (TimothyAsirJeyasing) [reply tendrl/commons/tests/flows/expand_cluster/test_ec_init.py:1]: Done

File: setup.py [hunk 2]
```diff
@@ -7,7 +7,7 @@
 
 try:
     # Python 2 backwards compat
-    from __builtin__ import raw_input as input
+    from builtins import raw_input as input
```
Comment (aruniiird) [inline setup.py]: the above line is giving following error in my python3 setup,
```python
>>> from builtins import raw_input as input
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'raw_input' from 'builtins' (unknown location)
>>> 
```
you may have to change it to,
```python
from six.moves import input
```
this will work in both python 2.7 and 3.x (tested on python 2.7.16 and python 3.7.5)

**Comment by TimothyAsirJeyasing** [comment]
@GowthamShanmugam , @shtripat Please review

File: tendrl/commons/utils/central_store/utils.py [hunk 3]
```diff
@@ -2,7 +2,7 @@
 import datetime
 import etcd
 import sys
-import thread
+import _thread
```
Comment (aruniiird) [inline tendrl/commons/utils/central_store/utils.py:5]:
```suggestion
import _thread as thread
```
then you don't have to change anywhere else

**Review by aruniiird — CHANGES_REQUESTED** [review]

File: tendrl/commons/utils/central_store/fields.py [hunk 4]
```diff
@@ -244,7 +244,7 @@ def _set_value(self, value):
 
         # Force casting if we were given a caster.
         if self._caster:
-            for x in value.keys():
+            for x in list(value.keys()):
```
Comment (GowthamShanmugam) [inline tendrl/commons/utils/central_store/fields.py]: I am seeing these changes in a few places, it is not necessary to convert this list by default it will give the result in list only. 

But not sure please check :)

Comment (GowthamShanmugam) [reply tendrl/commons/utils/central_store/fields.py]: no need list(value.keys()) or list((value.values()) or len(list((value.keys())) no need list conversion if i am right

**Review by GowthamShanmugam — COMMENTED** [review]
only minor suggestion, not change LGTM

File: setup.py (hunk 2 above)
Comment (GowthamShanmugam) [reply setup.py]: can you try this: 
    from builtins import input

no need alias, raw_input is renamed as input

Comment (TimothyAsirJeyasing) [reply setup.py]: Thank you, I will do it!

File: tendrl/commons/utils/central_store/utils.py (hunk 3 above)
Comment (TimothyAsirJeyasing) [reply tendrl/commons/utils/central_store/utils.py:5]: Sure thank you

File: tendrl/commons/utils/central_store/fields.py (hunk 4 above)
Comment (TimothyAsirJeyasing) [reply tendrl/commons/utils/central_store/fields.py]: Done

**Comment by TimothyAsirJeyasing** [comment]
Have done the review changes. Please review @GowthamShanmugam , @aruniiird

File: tendrl/commons/objects/cluster/atoms/import_cluster/__init__.py [hunk 5]
```diff
@@ -42,7 +42,7 @@ def run(self):
                 cmd = cmd_utils.Command('gluster volume list')
                 out, err, rc = cmd.run()
                 if not err:
-                    volumes = filter(None, out.split("\n"))
+                    volumes = [_f for _f in out.split("\n") if _f]
```
Comment (aruniiird) [inline tendrl/commons/objects/cluster/atoms/import_cluster/__init__.py]: Instead of "\n" , isn't it a good idea to use, `os.linesep` (which will give more interoperability), but leaving this at your discretion.

**Review by aruniiird — COMMENTED** [review]
A minor comment, nothing much to review here...

File: tendrl/commons/objects/cluster/atoms/import_cluster/__init__.py (hunk 5 above)
Comment (TimothyAsirJeyasing) [reply tendrl/commons/objects/cluster/atoms/import_cluster/__init__.py]: This patch is mainly for python3 convert. However we can do this kind of enhancement at later point of time. Thank you.
